ARG version
FROM almalinux:${version:-9}
ENV COURSE="DevOps" \
    DURATION="120HRS"  

ARG TRAINER="JohnDoe"     
RUN echo "Hi, Course is ${COURSE}, duration  is  ${DURATION} and trainer is ${TRAINER}" 
CMD ["sleep", "1000"]